// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_Web_Api.Infrastructure;

#nullable disable

namespace REST_Web_Api.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20260513002822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("REST_Web_Api.Models.ComponentManufacturers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTEL",
                            FoundationDate = new DateTime(1982, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel Group"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateTime(1962, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nvidia Group"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "Corsair",
                            FoundationDate = new DateTime(1992, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Corsair Group"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "Kingston",
                            FoundationDate = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Kingston Group"
                        });
                });

            modelBuilder.Entity("REST_Web_Api.Models.ComponentTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        });
                });

            modelBuilder.Entity("REST_Web_Api.Models.Components", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturesld")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesld")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturesld");

                    b.HasIndex("ComponentTypesld");

                    b.ToTable("Components", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "I7-6950K",
                            ComponentManufacturesld = 1,
                            ComponentTypesld = 1,
                            Description = "Intel Core i7-6950K",
                            Name = "Intel Core i7-6950K"
                        },
                        new
                        {
                            Code = "RTX5090",
                            ComponentManufacturesld = 2,
                            ComponentTypesld = 2,
                            Description = "New nvidia graphic card",
                            Name = "NVIDIA Geforce RTX 5090"
                        },
                        new
                        {
                            Code = "DDR5 16GB",
                            ComponentManufacturesld = 3,
                            ComponentTypesld = 3,
                            Description = "16GB (2x8GB) 6000MHz RAM",
                            Name = "DDR5 16GB RAM"
                        },
                        new
                        {
                            Code = "DDR4 16GB",
                            ComponentManufacturesld = 4,
                            ComponentTypesld = 3,
                            Description = "16GB (2x8GB) 6000MHz RAM",
                            Name = "DDR4 16GB RAM"
                        });
                });

            modelBuilder.Entity("REST_Web_Api.Models.PCComponents", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents", (string)null);

                    b.HasData(
                        new
                        {
                            PCId = 2,
                            ComponentCode = "I7-6950K",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "RTX5090",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "DDR5 16GB",
                            Amount = 2
                        });
                });

            modelBuilder.Entity("REST_Web_Api.Models.PCs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PCs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cheap PC",
                            Stock = 10,
                            Warranty = 24,
                            Weight = 13f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Medium PC",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 16f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming PC",
                            Stock = 3,
                            Warranty = 12,
                            Weight = 22f
                        });
                });

            modelBuilder.Entity("REST_Web_Api.Models.Components", b =>
                {
                    b.HasOne("REST_Web_Api.Models.ComponentManufacturers", "ComponentManufacturers")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturesld")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REST_Web_Api.Models.ComponentTypes", "ComponentTypes")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesld")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturers");

                    b.Navigation("ComponentTypes");
                });

            modelBuilder.Entity("REST_Web_Api.Models.PCComponents", b =>
                {
                    b.HasOne("REST_Web_Api.Models.Components", "Components")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REST_Web_Api.Models.PCs", "PCs")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Components");

                    b.Navigation("PCs");
                });

            modelBuilder.Entity("REST_Web_Api.Models.ComponentManufacturers", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("REST_Web_Api.Models.ComponentTypes", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("REST_Web_Api.Models.Components", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("REST_Web_Api.Models.PCs", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
